const GET_SOURCE_REQUEST = "GET_SOURCE_REQUEST";
const GET_SOURCE_SUCCESS = "GET_SOURCE_SUCCESS";
const GET_SOURCE_FAIL = "GET_SOURCE_FAIL";


const GET_HEADLINE_REQUEST = "GET_HEADLINE_REQUEST";
const GET_HEADLINE_SUCCESS = "GET_HEADLINE_SUCCESS";
const GET_HEADLINE_FAIL = "GET_HEADLINE_FAIL";

const GET_NEWSDATA = "GET_NEWSDATA";

export {
  GET_SOURCE_REQUEST,
  GET_SOURCE_SUCCESS,
  GET_SOURCE_FAIL,
  GET_HEADLINE_REQUEST,
  GET_HEADLINE_SUCCESS,
  GET_HEADLINE_FAIL,
  GET_NEWSDATA
};
